name: Build package

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install system dependencies
      run: sudo apt update && sudo apt install -y --no-install-recommends python3-setuptools python3-wheel && pip3 install twine

    - name: Build package
      run: python3 setup.py sdist bdist_wheel

    - name: Twine check
      run: python3 -m twine check dist/*
